package commands.enums;

public enum CommandType {

    CREATENEWTEAM,
    CREATENEWBOARDINTEAM,
    CREATENEWPERSON,
    ADDPERSONTOTEAM,
    CREATENEWFEEDBACKINBOARD,
    CREATENEWBUGINBOARD,
    CREATENEWSTORYINBOARD,
    ADDCOMMENTTOTASK,
    ASSIGNTASKTOPERSON,
    CHANGEPRIORITYINBUG,
    CHANGEPRIORITYINSTORY,
    CHANGERATINGINFEEDBACK,
    CHANGESEVERITYINBUG,
    CHANGESIZEINSTORY,
    CHANGESTATUSINBUG,
    CHANGESTATUSINFEEDBACK,
    CHANGESTATUSINSTORY,
    SHOWALLPEOPLE,
    SHOWBOARDSACTIVITY,
    SHOWPERSONACTIVITY,
    SHOWTEAMBOARDS,
    SHOWTEAMMEMBERS,
    SHOWTEAMSACTIVITY,
    SHOWTEAMS,
    UNASSIGNTASKTOPERSON,
    LISTBUGS,
    LISTFEEDBACKS,
    LISTSTORIES,
    LISTTASKS,
    LISTTASKSWITHASSIGNEE,
    SHOWBUGSTEPSTOREPRODUCE,
    MANUAL


}
